- DFC.App.Help/Controllers/BaseController.cs
- DFC.App.Help/Controllers/PagesController.cs
- DFC.App.Help/ViewModels/BreadcrumbViewModel.cs
- DFC.App.Help/ViewModels/DocumentViewModel.cs
- DFC.App.Help/ViewModels/IndexDocumentViewModel.cs
- DFC.App.Help/ViewModels/IndexViewModel.cs
- DFC.App.Help/Views/Pages/Breadcrumb.cshtml
- DFC.App.Help/Views/Pages/Document.cshtml
- DFC.App.Help/Views/Pages/Index.cshtml
- DFC.App.Help/Views/Shared/_ValidationScriptsPartial.cshtml
Updated create/update POST method
> Dev ian dfc 9509

- DFC.App.Help.IntegrationTests/ServiceTests/HelpPageServiceTests/HelpPageServiceCreateTests.cs
- DFC.App.Help.IntegrationTests/ServiceTests/HelpPageServiceTests/HelpPageServiceDeleteTests.cs
- DFC.App.Help.IntegrationTests/ServiceTests/HelpPageServiceTests/HelpPageServiceGetAllTests.cs
- DFC.App.Help.IntegrationTests/ServiceTests/HelpPageServiceTests/HelpPageServiceGetByIdTests.cs
- DFC.App.Help.IntegrationTests/ServiceTests/HelpPageServiceTests/HelpPageServiceGetByNameTests.cs
- DFC.App.Help.IntegrationTests/ServiceTests/HelpPageServiceTests/HelpPageServiceUpdateTests.cs
- DFC.App.Help/Controllers/PagesController.cs
- DFC.App.Help/Cosmos/Provider/DocumentDBProvider.cs
- DFC.App.Help/Models/Cosmos/HelpPageModel.cs
- DFC.App.Help/Services/HelpPageService.cs
- DFC.App.Help/ViewModels/DocumentViewModel.cs
- DFC.App.Help/Views/Pages/Document.cshtml
Removed siteinfiityId.
DocumentId must now always be provided
> Support for delete.

- DFC.App.Help/Cosmos/Provider/DocumentDBProvider.cs
- DFC.App.Help/Views/Pages/Document.cshtml
Added alternative name search on the url field
> Made name search by lower case.

- Resources/ArmTemplates/parameters.json
- Resources/ArmTemplates/template.json
- Resources/ArmTemplates/test-parameters.json
> NCSD-982: app settings

- DFC.App.Help.IntegrationTests/ServiceTests/HelpPageServiceTests/HelpPageServicePingTests.cs
- DFC.App.Help/Controllers/HealthController.cs
- DFC.App.Help/Controllers/PagesController.cs
- DFC.App.Help/Cosmos/Provider/DocumentDBProvider.cs
- DFC.App.Help/Cosmos/Provider/IDocumentDBProvider.cs
- DFC.App.Help/Services/HelpPageService.cs
- DFC.App.Help/Services/IHelpPageService.cs
- DFC.App.Help/ViewModels/HealthItemViewModel.cs
- DFC.App.Help/ViewModels/HealthViewModel.cs
- DFC.App.Help/Views/Health/Health.cshtml
2) Added health/ping endpoint to respond with OK
> 1) Added pages/contents/health endpoint to determine and return health status

- DFC.App.Help.IntegrationTests/ServiceTests/HelpPageServiceTests/BaseHelpPageServiceTests.cs
- DFC.App.Help.IntegrationTests/ServiceTests/HelpPageServiceTests/HelpPageServiceGetByAlternativeNameTests.cs
- DFC.App.Help/Controllers/BaseController.cs
- DFC.App.Help/Controllers/PagesController.cs
Added unit tests to improve code coverage.
> Refactored automapper name.

- DFC.App.Help.Data/DFC.App.Help.Data.csproj
- DFC.App.Help.IntegrationTests/DFC.App.Help.IntegrationTests.csproj
- DFC.App.Help.PageService.UnitTests/DFC.App.Help.PageService.UnitTests.csproj
- DFC.App.Help.PageService/DFC.App.Help.PageService.csproj
- DFC.App.Help.Repository.CosmosDb/DFC.App.Help.Repository.CosmosDb.csproj
- DFC.App.Help.UnitTests/DFC.App.Help.UnitTests.csproj
- DFC.App.Help/DFC.App.Help.csproj
- stylecop.json
- Stylecop basic rule file added to all the projects.
> Added the default stylecion settings file

- DFC.App.DraftHelp.PageService/DFC.App.DraftHelp.PageService.csproj
- DFC.App.DraftHelp.PageService/DraftHelpPageService.cs
- DFC.App.Help.Data/Contracts/IDraftHelpPageService.cs
- DFC.App.Help.Data/Contracts/IHelpPageService.cs
- DFC.App.Help.Data/Contracts/IRepository.cs
- DFC.App.Help.IntegrationTests/DFC.App.Help.IntegrationTests.csproj
- DFC.App.Help.IntegrationTests/ServiceTests/BaseServiceTests.cs
- DFC.App.Help.PageService.UnitTests/HelpPageServiceTests/HelpPageServiceCreateTests.cs
- DFC.App.Help.PageService.UnitTests/HelpPageServiceTests/HelpPageServiceDeleteTests.cs
- DFC.App.Help.PageService.UnitTests/HelpPageServiceTests/HelpPageServiceGetAllTests.cs
- DFC.App.Help.PageService.UnitTests/HelpPageServiceTests/HelpPageServiceGetByAlternativeNameTests.cs
- DFC.App.Help.PageService.UnitTests/HelpPageServiceTests/HelpPageServiceGetByIdTests.cs
- DFC.App.Help.PageService.UnitTests/HelpPageServiceTests/HelpPageServiceGetByNameTests.cs
- DFC.App.Help.PageService.UnitTests/HelpPageServiceTests/HelpPageServicePingTests.cs
- DFC.App.Help.PageService.UnitTests/HelpPageServiceTests/HelpPageServiceUpdateTests.cs
- DFC.App.Help.PageService/HelpPageService.cs
- DFC.App.Help.PagesModule.UnitTests/ControllerTests/PagesControllerTests/PagesControllerDraftTests.cs
- DFC.App.Help.sln
- DFC.App.Help/Controllers/BaseController.cs
- DFC.App.Help/Controllers/HealthController.cs
- DFC.App.Help/Controllers/PagesController.cs
- DFC.App.Help/Controllers/SitemapController.cs
- DFC.App.Help/DFC.App.Help.csproj
- DFC.App.Help/Extensions/HttpRequestExtensions.cs
- DFC.App.Help/Startup.cs
- Merged in dev branch following Ians PR
- Added draft help service that simply returns hardcoded JSON to simulate API response from SF
> Added Draft Help routes and mock service

- Resources/AzureDevOps/azure-pipelines.yml
Updated YAML build in line with other dfc-apps
> NCSD-1453: Update YAML build

- Resources/ArmTemplates/template.json
Fixes the name of the Azure resources created by changing the prefix variable
> NCSD-1860: Resources name fix

- Resources/ArmTemplates/template.json
- Resources/AzureDevOps/azure-pipelines.yml
Rename of
* solution for Azure YAML build pipeline
* app settings
* Cosmos partition key
> NCSD-2328 rename of solution

- Resources/ArmTemplates/template.json
Bring DatabaseId app setting into line with job profiles
> NCSD-2331: App setting change

- Resources/ArmTemplates/parameters.json
- Resources/ArmTemplates/template.json
- Resources/ArmTemplates/test-parameters.json
- Resources/AzureDevOps/azure-pipelines.yml
Updated the YAML file to build the function app and the ARM template to create the function app + associated app insight
> NCSD-2359: Function app

- .gitignore
- Resources/PageRegistration/registration.json
registration.json had HeathCheck instead of HealthCheck which causes problems with diff model
> NCSD-2338: Fixed typo in registration.json

- Resources/ArmTemplates/parameters.json
- Resources/ArmTemplates/template.json
Added subscription to the service bus topic with optional SQL filter
> NCSD-2391: Added subscription with SQLfilter

- Resources/PageRegistration/registration.json
- Make alerts regions default to Healthy (#82)
- Make all regions healthy by default and prevent func app from marking it to un-healthy (#81)
> Release v1.1.33.1

- Resources/AzureDevOps/azure-pipelines.yml
Change dotnet core version used for the build
> DFC-12205: YAML build

- Resources/ArmTemplates/template.json
Enable zero down time web app deployment for all stages
> deployStagingSlot: true

- Resources/ArmTemplates/template.json
- Resources/AzureDevOps/azure-pipelines.yml
- Added support for blue green deployment
- Updated pipeline
> Release v1.1.44.2

- Resources/PageRegistration/registration.json
Removed help from registration document
> Release v1.1.44.3

- Resources/PageRegistration/registration.json
And reinstated help registration
> added IsOnline = true to cont pages

- Resources/PageRegistration/registration.json
- Help registration added back for CUI footer
- App online flag set to true during registration
> Release v1.1.44.4
